<?php
$title = "Welcome";                   // (1) Set the title
include "include\header.php";                 // (2) Include the header
?>
<html>
<head>
	<link rel="stylesheet" type="text/css" href="stylesheet\design.css">
</head>
<body>
	<p><img src="book7.jpg" alt="BOOK1" style="width:170px;height:170px;margin-left:15px;">The English language is among the leading languages in terms of usage all over the world. As such, it can be said that as a language, it plays a very important role in the everyday running of countries and the world at large.
   English language provides an insight into diverse cultures. Being based on a basic alphabet, it easy and quick to learn compared to the other languages.</p>
   <p><img src="book6.jpg" alt="BOOK2" style="width:170px;height:170px;margin-left:15px;">Because English language is spoken in many parts of India, many of the schools have integrated it into their programmes as they know it makes students liable to more opportunities.English language is used in many of the Indian websites on the internet and therefore knowing the language gives you access to many websites so that you can participate in forums and discussions over the internet.English is among the popular language of the India media industry therefore understanding it eliminates the need for translations so you can enjoy books, movies, songs and TV shows.There is a lot of people to meet and speak to in English. Learning English language therefore increases one’s chances of securing a good employment in one’s country as well as abroad..</p>
   <p><img src="book4.jpg" alt="BOOK3" style="width:170px;height:170px;margin-left:15px;">Many Multinational companies locally and internationally now use the knowledge of the English language as a criterion for employment because they appreciate the role played by English language in the 21st Century economy. Similarly, individuals are seeking to learn the language with the intention of expanding opportunities for themselves career wise.</p>
   <p><img src="book3.jpg" alt="BOOK4" style="width:170px;height:170px;margin-left:15px;">English is one of the widely spoken global languages. In a globalised world, the English language is not just a language but an important asset. The ability to speak English comes with the benefit of access to the global world. English language has put India in the global market. The individual as well as the economy benefit from the use of English language.Learning the English language is important because it increases the horizon for the individual. We live in a diverse world with a variety of cultures and languages. English has emerged as dominant language and this knowledge is helps us connect beyond our cultural boundaries. From work to academic exchange to business, English language helps us connect at a global level. International trade, academic exchange, cultural exchange and many others have been enabled and improved by English language.</p>
   <p><img src="book7.jpg" alt="BOOK4" style="width:170px;height:170px;margin-left:15px;">English has been a game changer for the Indian economy. The nation adopted English language quickly because of the British colonisation in the past. It has proved to be helpful in the globalised era. The availability of English educated youth has provided a boost for the service industry in India. It has enabled us to be a low cost source for business services such as BPO, banking, customer service and many others. The big boom in the Indian IT industry has been supported by the knowledge of English.</p>
   <p><img src="book4.jpg" alt="BOOK4" style="width:170px;height:170px;margin-left:15px;">Cultural and educational exchange has been enabled by English. The tourism industry relies on English language. It gives it an operational advantage by making it relatively easier to reach international tourists. Education has also benefitted through the exchange of developments in the various disciplines. Researchers across India and academic circles are now being able to connect and work together because of the English language. English language is very beneficial in today’s technologically driven globalised world by enabling various kinds of exchange from trade, to culture and education..</p>
</body>
</html>
<?php
include "include/footer.php";                 // (3) Include the footer
?>